// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkBeast.Data.Context;

#nullable disable

namespace WorkBeast.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203150143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("BodyPartExercise", b =>
                {
                    b.Property<int>("ExercisesOid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetedBodyPartsOid")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExercisesOid", "TargetedBodyPartsOid");

                    b.HasIndex("TargetedBodyPartsOid");

                    b.ToTable("BodyPartExercise");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.BodyPart", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.ToTable("BodyParts");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.Exercise", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.ExerciseBodyPart", b =>
                {
                    b.Property<int>("ExerciseOid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyPartOid")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExerciseOid", "BodyPartOid");

                    b.HasIndex("BodyPartOid");

                    b.ToTable("ExerciseBodyPart");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.LoggedExercise", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseOid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionOid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Oid");

                    b.HasIndex("ExerciseOid");

                    b.HasIndex("Sequence");

                    b.HasIndex("WorkoutSessionOid");

                    b.ToTable("LoggedExercises");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.HasIndex("Date");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedExerciseOid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResistanceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Oid");

                    b.HasIndex("LoggedExerciseOid");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("BodyPartExercise", b =>
                {
                    b.HasOne("WorkBeast.Core.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkBeast.Core.Models.BodyPart", null)
                        .WithMany()
                        .HasForeignKey("TargetedBodyPartsOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkBeast.Core.Models.ExerciseBodyPart", b =>
                {
                    b.HasOne("WorkBeast.Core.Models.BodyPart", "BodyPart")
                        .WithMany()
                        .HasForeignKey("BodyPartOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkBeast.Core.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.LoggedExercise", b =>
                {
                    b.HasOne("WorkBeast.Core.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkBeast.Core.Models.WorkoutSession", null)
                        .WithMany("LoggedExercises")
                        .HasForeignKey("WorkoutSessionOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.WorkoutSet", b =>
                {
                    b.HasOne("WorkBeast.Core.Models.LoggedExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("LoggedExerciseOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkBeast.Core.Models.LoggedExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkBeast.Core.Models.WorkoutSession", b =>
                {
                    b.Navigation("LoggedExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
